id: A369C714C
title: Prayer for the Swift Rebirth of Dodrupchen Rinpoche
type: translation
pechas:
- I9468A688
- I242F2767
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:55:22.462271
  last_modified_at: 2023-01-04 11:55:22.462282
  collections:
  - Fourth Dodrupchen Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I9468A688/DA50: F36A
  I242F2767/D6F1: F36A
